# Generated by Django 5.0.3 on 2026-04-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('barista', 'Barista'), ('cocinero', 'Cocinero')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tipo',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida')], default='comida', max_length=20),
        ),
    ]
