# Generated by Django 5.2.12 on 2026-03-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Nombre del ícono Lucide (ej: leaf, coffee, utensils)', max_length=50, verbose_name='Ícono')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número menor = aparece primero en el kiosk', verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del grupo')),
                ('requerido', models.BooleanField(default=False, help_text='El cliente debe elegir al menos una opción', verbose_name='Requerido')),
                ('min_select', models.PositiveIntegerField(default=0, verbose_name='Mínimo de selecciones')),
                ('max_select', models.PositiveIntegerField(default=1, verbose_name='Máximo de selecciones')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Grupo de modificadores',
                'verbose_name_plural': 'Grupos de modificadores',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0.0, help_text='0.00 si no tiene costo adicional', max_digits=6, verbose_name='Precio extra')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.modifiergroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Modificador',
                'verbose_name_plural': 'Modificadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio base')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('disponible', models.BooleanField(default=True, help_text='Desmarca para ocultar temporalmente sin desactivar', verbose_name='Disponible')),
                ('activo', models.BooleanField(default=True, help_text='Desactiva para eliminar del menú de forma permanente', verbose_name='Activo')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='menu.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category__orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='menu.product', verbose_name='Producto'),
        ),
    ]
